# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placardintelel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference_tag',
            name='id',
        ),
        migrations.AddField(
            model_name='historique_receptions',
            name='masse',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historique_receptions',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='placardintelel.REFERENCE_TAG'),
        ),
        migrations.AddField(
            model_name='masse_actuelle',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='placardintelel.REFERENCE_TAG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masse_prelevee',
            name='masse',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masse_prelevee',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='placardintelel.REFERENCE_TAG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference_tag',
            name='id_tag',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historique_receptions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
