# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placardintelel', '0002_auto_20160617_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_tag',
            name='id_tag',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
